# Generated by Django 4.2.7 on 2023-11-29 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_id_no_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='id_no',
            new_name='ID_no',
        ),
    ]
