# Generated by Django 4.2.7 on 2023-11-25 09:20

from django.db import migrations, models
import django.utils.timezone
import document_manager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to=document_manager.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'folder',
                'verbose_name_plural': 'folders',
            },
        ),
    ]
